apiVersion: v1
kind: Namespace
metadata:
  name: frigate


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  namespace: frigate
spec:
  selector:
    matchLabels:
      app: frigate
  replicas: 0
  template:
    metadata:
      labels:
        app: frigate
    spec:
      containers:
      - name: frigate
        image: ghcr.io/blakeblackshear/frigate:stable
        env:
        - name: FRIGATE_RTSP_PASSWORD
          value: 'password'
        securityContext:
          privileged: true
        ports:
        - containerPort: 5000
        - containerPort: 1935
        - containerPort: 8554
        volumeMounts:
          - name: frigate-pv-data
            mountPath: "/config"
          - name: frigate-pv-media
            mountPath: "/media"
          
      volumes:
      - name: frigate-pv-data
        persistentVolumeClaim:
          claimName: frigatepvc-data
      - name: frigate-pv-media
        persistentVolumeClaim:
          claimName: frigatepvc-media
      
---
apiVersion: v1
kind: Service
metadata:
  name: frigate
  namespace: frigate
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.0.243
spec:
  selector:
    app: frigate
  ports:
    - protocol: TCP
      port: 5000
      name: http
    - protocol: TCP
      port: 1935
      name: test
    - protocol: TCP
      port: 8554
      name: rtsp
  type: LoadBalancer
