apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streamedia
  namespace: ffmpeg
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "5Gi"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: ffmpeg-job
  namespace: ffmpeg
spec:
  template:
    spec:
      containers:
      - name: ffmpeg-container
        image: linuxserver/ffmpeg
        command: ["ffmpeg"]
        args:
        - "-re"
        - "-stream_loop"
        - "-1"
        - "-i"
        - "/media/lefties-720.mp4"
        - "-f"
        - "rtsp"
        - "rtsp://192.168.0.242:8554/live/stream"
        volumeMounts:
        - name: media
          mountPath: /media
      restartPolicy: Never
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: streamedia  # Replace 'my-pvc' with the name of your PVC
  backoffLimit: 4  # Optional: Number of retries before considering the Job as failed
