apiVersion: v1
kind: Namespace
metadata:
  name: mediatx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: mediatx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: bluenviron/mediamtx:latest-ffmpeg-rpi
        ports:
        - containerPort: 8080
