apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigatepvc-data
  namespace: frigate-server
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "1Gi"
